[app]
host = "127.0.0.1"
port = 8080

[database]
host = "localhost"
port = 5432
user = "ucup"
password = "ucup@123"
db_name = "book_stock"

[jwt]
access_token_secret = "secret here"
refresh_token_secret = "secret here"
