// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/books": {
            "get": {
                "description": "Get a list of books with pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "books"
                ],
                "summary": "Get books with pagination",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page offset (default: 0)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page limit (default: 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Books information with pagination metadata",
                        "schema": {
                            "$ref": "#/definitions/model.PaginatedResponse-model_BookResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid query parameters",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Failed to get books",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new book with the provided information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "books"
                ],
                "summary": "Create a new book",
                "parameters": [
                    {
                        "description": "Request payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateBookRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Book created",
                        "schema": {
                            "$ref": "#/definitions/model.BookResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request payload",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Failed to create book",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update book information partially",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "books"
                ],
                "summary": "Update book",
                "parameters": [
                    {
                        "description": "Request payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateBookRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated book",
                        "schema": {
                            "$ref": "#/definitions/model.BookResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request payload",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Book not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Failed to update book",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/books/isbn/{isbn}": {
            "get": {
                "description": "Get a book information by ISBN",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "books"
                ],
                "summary": "Get book by ISBN",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ISBN",
                        "name": "isbn",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Book information",
                        "schema": {
                            "$ref": "#/definitions/model.BookResponse"
                        }
                    },
                    "400": {
                        "description": "ISBN is required",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Book not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Failed to get book by ISBN",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/books/{book_id}": {
            "get": {
                "description": "Get a book information by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "books"
                ],
                "summary": "Get book by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Book ID",
                        "name": "book_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Book information",
                        "schema": {
                            "$ref": "#/definitions/model.BookResponse"
                        }
                    },
                    "400": {
                        "description": "Book ID is required",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Book not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Failed to get book by ID",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete book by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "books"
                ],
                "summary": "Delete book",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Book ID",
                        "name": "book_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Book ID is required",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Book not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Failed to delete book",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.BookResponse": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string",
                    "example": "Tere Liye"
                },
                "book_id": {
                    "type": "string",
                    "example": "b2a0f3c4-5d8e-4c1b-9f7e-2d3f4e5a6b7c"
                },
                "isbn": {
                    "type": "string",
                    "example": "978-3-16-148410-0"
                },
                "published_at": {
                    "type": "string",
                    "example": "2016-01-28"
                },
                "publisher": {
                    "type": "string",
                    "example": "Gramedia"
                },
                "stock": {
                    "type": "integer",
                    "example": 200
                },
                "title": {
                    "type": "string",
                    "example": "Hujan"
                }
            }
        },
        "model.CreateBookRequest": {
            "type": "object",
            "required": [
                "author",
                "isbn",
                "published_at",
                "publisher",
                "stock",
                "title"
            ],
            "properties": {
                "author": {
                    "type": "string",
                    "example": "Tere Liye"
                },
                "isbn": {
                    "type": "string",
                    "example": "9783161484100"
                },
                "published_at": {
                    "type": "string",
                    "example": "2016-01-28"
                },
                "publisher": {
                    "type": "string",
                    "example": "Gramedia"
                },
                "stock": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 200
                },
                "title": {
                    "type": "string",
                    "example": "Hujan"
                }
            }
        },
        "model.PaginatedResponse-model_BookResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.BookResponse"
                    }
                },
                "links": {
                    "$ref": "#/definitions/model.PaginationLinks"
                },
                "meta": {
                    "$ref": "#/definitions/model.PaginationMeta"
                }
            }
        },
        "model.PaginationLinks": {
            "type": "object",
            "properties": {
                "first": {
                    "type": "string",
                    "example": "/api/v1/books?offset=0\u0026limit=10"
                },
                "last": {
                    "type": "string",
                    "example": "/api/v1/books?offset=90\u0026limit=10"
                },
                "next": {
                    "type": "string",
                    "example": "/api/v1/books?offset=10\u0026limit=10"
                },
                "prev": {
                    "type": "string",
                    "example": "/api/v1/books?offset=0\u0026limit=10"
                },
                "self": {
                    "type": "string",
                    "example": "/api/v1/books?offset=0\u0026limit=10"
                }
            }
        },
        "model.PaginationMeta": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer",
                    "example": 10
                },
                "offset": {
                    "type": "integer",
                    "example": 0
                },
                "total": {
                    "type": "integer",
                    "example": 100
                }
            }
        },
        "model.UpdateBookRequest": {
            "type": "object",
            "required": [
                "book_id"
            ],
            "properties": {
                "author": {
                    "type": "string",
                    "example": "Tere Liye"
                },
                "book_id": {
                    "type": "string"
                },
                "isbn": {
                    "type": "string",
                    "example": "9783161484100"
                },
                "published_at": {
                    "type": "string",
                    "example": "2016-01-28"
                },
                "publisher": {
                    "type": "string",
                    "example": "Gramedia"
                },
                "stock": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 200
                },
                "title": {
                    "type": "string",
                    "example": "Hujan"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Book Stock Manager API",
	Description:      "Backend API service for Book Stock Manager",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
